
template: Hello, %s!
defaultName: Stranger

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: password
  url: jdbc:mysql://localhost:3306/my_db
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  minSize: 5
  maxSize: 20