/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2025-08-12 20:18:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Stock Search</title>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("  <style>\r\n");
      out.write("    body { font-family: system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif; margin: 2rem; }\r\n");
      out.write("    h1 { margin-bottom: 1rem; }\r\n");
      out.write("    form { display: grid; grid-template-columns: 2fr auto; gap: .75rem; max-width: 700px; align-items: end; }\r\n");
      out.write("    label { display: grid; gap: .25rem; font-size: .9rem; }\r\n");
      out.write("    input { padding: .55rem .6rem; font-size: 1rem; }\r\n");
      out.write("    button { padding: .6rem 1rem; font-size: 1rem; cursor: pointer; }\r\n");
      out.write("    #status { margin-top: 1rem; font-size: .95rem; color: #555; }\r\n");
      out.write("    table { width: 100%; border-collapse: collapse; margin-top: .75rem; }\r\n");
      out.write("    th, td { border: 1px solid #e2e2e2; padding: .45rem .55rem; text-align: left; }\r\n");
      out.write("    th { background: #f8f8f8; }\r\n");
      out.write("    .num { text-align: right; white-space: nowrap; }\r\n");
      out.write("    .pos { color: #0a7a00; }\r\n");
      out.write("    .neg { color: #b10000; }\r\n");
      out.write("    .hint { font-size: .85rem; color: #666; margin-top: .25rem; }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>Stock Search</h1>\r\n");
      out.write("\r\n");
      out.write("<form id=\"frm\" method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/api/search\">\r\n");
      out.write("  <label>Ticker\r\n");
      out.write("    <input type=\"text\" name=\"q\" id=\"q\" required placeholder=\"e.g. AAPL\" />\r\n");
      out.write("    <div class=\"hint\">Search one ticker at a time.</div>\r\n");
      out.write("  </label>\r\n");
      out.write("  <button type=\"submit\">Search</button>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<div id=\"status\">Enter a ticker and press Search.</div>\r\n");
      out.write("\r\n");
      out.write("<table id=\"results\" hidden>\r\n");
      out.write("  <thead>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <th>Symbol</th>\r\n");
      out.write("    <th>Name</th>\r\n");
      out.write("    <th class=\"num\">Price</th>\r\n");
      out.write("    <th class=\"num\">Prev Close</th>\r\n");
      out.write("    <th class=\"num\">Change</th>\r\n");
      out.write("    <th class=\"num\">Change %</th>\r\n");
      out.write("    <th class=\"num\">Volume</th>\r\n");
      out.write("    <th>As Of</th>\r\n");
      out.write("  </tr>\r\n");
      out.write("  </thead>\r\n");
      out.write("  <tbody></tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<noscript>\r\n");
      out.write("  <p><em>JavaScript is disabled. The form will submit to the server and render results via JSP.</em></p>\r\n");
      out.write("</noscript>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  (function () {\r\n");
      out.write("    const frm = document.getElementById('frm');\r\n");
      out.write("    const statusEl = document.getElementById('status');\r\n");
      out.write("    const table = document.getElementById('results');\r\n");
      out.write("    const tbody = table.querySelector('tbody');\r\n");
      out.write("\r\n");
      out.write("    const fmt = (v) => (v === null || v === undefined) ? '' : String(v).replace(/[<>&\"']/g, function(m) {\r\n");
      out.write("      return {'<':'&lt;','>':'&gt;','&':'&amp;','\"':'&quot;',\"'\":'&#39;'}[m];\r\n");
      out.write("    });\r\n");
      out.write("    const fmtNum = (v) => (v === null || v === undefined || isNaN(v)) ? '' : Number(v).toLocaleString();\r\n");
      out.write("    const fmtPct = (v) => (v === null || v === undefined || isNaN(v)) ? '' : (Number(v).toFixed(2) + '%');\r\n");
      out.write("    const n = (v) => (v === null || v === undefined || v === '') ? '' : Number(v);\r\n");
      out.write("    const signCls = (v) => (v == null || isNaN(v)) ? '' : (Number(v) >= 0 ? 'pos' : 'neg');\r\n");
      out.write("    const fmtTs = (ms) => (ms ? new Date(ms).toLocaleString() : '');\r\n");
      out.write("\r\n");
      out.write("    frm.addEventListener('submit', async function (e) {\r\n");
      out.write("      if (!window.fetch) return;\r\n");
      out.write("      e.preventDefault();\r\n");
      out.write("\r\n");
      out.write("      const q = document.getElementById('q').value.trim();\r\n");
      out.write("      const payload = { q };\r\n");
      out.write("\r\n");
      out.write("      statusEl.textContent = 'Searching…';\r\n");
      out.write("      table.hidden = true;\r\n");
      out.write("      tbody.innerHTML = '';\r\n");
      out.write("\r\n");
      out.write("      try {\r\n");
      out.write("        const res = await fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/api/filter', {\r\n");
      out.write("          method: 'POST',\r\n");
      out.write("          headers: { 'Content-Type': 'application/json' },\r\n");
      out.write("          body: JSON.stringify(payload)\r\n");
      out.write("        });\r\n");
      out.write("        if (!res.ok) throw new Error('HTTP ' + res.status);\r\n");
      out.write("        const data = await res.json();\r\n");
      out.write("\r\n");
      out.write("        if (!Array.isArray(data) || data.length === 0) {\r\n");
      out.write("          statusEl.textContent = 'No results.';\r\n");
      out.write("          return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        data.forEach(function(r) {\r\n");
      out.write("          const tr = document.createElement('tr');\r\n");
      out.write("\r\n");
      out.write("          const symbolTd = document.createElement('td');\r\n");
      out.write("          symbolTd.textContent = fmt(r.symbol);\r\n");
      out.write("          tr.appendChild(symbolTd);\r\n");
      out.write("\r\n");
      out.write("          const nameTd = document.createElement('td');\r\n");
      out.write("          nameTd.textContent = fmt(r.name);\r\n");
      out.write("          tr.appendChild(nameTd);\r\n");
      out.write("\r\n");
      out.write("          const priceTd = document.createElement('td');\r\n");
      out.write("          priceTd.className = 'num';\r\n");
      out.write("          priceTd.textContent = fmtNum(n(r.price));\r\n");
      out.write("          tr.appendChild(priceTd);\r\n");
      out.write("\r\n");
      out.write("          const prevCloseTd = document.createElement('td');\r\n");
      out.write("          prevCloseTd.className = 'num';\r\n");
      out.write("          prevCloseTd.textContent = fmtNum(n(r.previousClose));\r\n");
      out.write("          tr.appendChild(prevCloseTd);\r\n");
      out.write("\r\n");
      out.write("          const changeTd = document.createElement('td');\r\n");
      out.write("          changeTd.className = 'num ' + signCls(n(r.change));\r\n");
      out.write("          changeTd.textContent = fmtNum(n(r.change));\r\n");
      out.write("          tr.appendChild(changeTd);\r\n");
      out.write("\r\n");
      out.write("          const changePctTd = document.createElement('td');\r\n");
      out.write("          changePctTd.className = 'num ' + signCls(n(r.changePercent));\r\n");
      out.write("          changePctTd.textContent = fmtPct(n(r.changePercent));\r\n");
      out.write("          tr.appendChild(changePctTd);\r\n");
      out.write("\r\n");
      out.write("          const volumeTd = document.createElement('td');\r\n");
      out.write("          volumeTd.className = 'num';\r\n");
      out.write("          volumeTd.textContent = fmtNum(n(r.volume));\r\n");
      out.write("          tr.appendChild(volumeTd);\r\n");
      out.write("\r\n");
      out.write("          const asOfTd = document.createElement('td');\r\n");
      out.write("          asOfTd.textContent = fmtTs(r.asOf);\r\n");
      out.write("          tr.appendChild(asOfTd);\r\n");
      out.write("\r\n");
      out.write("          tbody.appendChild(tr);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        statusEl.textContent = 'Done.';\r\n");
      out.write("        table.hidden = false;\r\n");
      out.write("      } catch (err) {\r\n");
      out.write("        statusEl.textContent = 'Error: ' + err.message;\r\n");
      out.write("        table.hidden = true;\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("  })();\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
